# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - cknapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://cknapp.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_1aa3a5dfd1f845338cdaf84d7bc03be6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_81d97ab74e50456993f088f85181e652 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: cknapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1aa3a5dfd1f845338cdaf84d7bc03be6 }}/chicken:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'cknapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_13fbd3d3707e4ec29ee90df60704c322 }}
        images: 'cknapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1aa3a5dfd1f845338cdaf84d7bc03be6 }}/chicken:${{ github.sha }}'